# pylint: skip-file
# Generated by Django 3.2.4 on 2021-06-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_dialog_engine', '0009_auto_20210614_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=256)),
                ('started', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_sessions', to='django_dialog_engine.dialog')),
            ],
        ),
    ]
