# pylint: skip-file
# Generated by Django 3.2.4 on 2021-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256)),
                ('dialog_key', models.CharField(blank=True, max_length=256, null=True)),
                ('key', models.CharField(max_length=1024)),
                ('value', models.TextField(max_length=4194304)),
                ('date_set', models.DateTimeField()),
            ],
        ),
    ]
