# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0012_dialogscript_embeddable'),
        ('simple_messaging_dialog_support', '0002_dialogvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogTemplateVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024)),
                ('value', models.TextField(max_length=4194304)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_variables', to='django_dialog_engine.DialogScript')),
            ],
        ),
        migrations.AlterField(
            model_name='dialogsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dialogvariable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
