# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0003_auto_20220314_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogtemplatevariable',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_variables', to='django_dialog_engine.DialogScript'),
        ),
    ]
