# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-05 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0012_dialogscript_embeddable'),
        ('simple_messaging_dialog_support', '0005_auto_20220425_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=1048576)),
                ('added', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_alerts', to='django_dialog_engine.Dialog')),
            ],
        ),
        migrations.AlterField(
            model_name='dialogsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dialogtemplatevariable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dialogvariable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
