# pylint: skip-file
# Generated by Django 3.2.13 on 2022-07-04 16:22

from django.db import migrations

try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):
    dependencies = [
        ('simple_messaging_dialog_support', '0006_auto_20220505_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogalert',
            name='metadata',
            field=JSONField(blank=True, null=True),
        ),
    ]
