# pylint: skip-file
# Generated by Django 3.2.18 on 2023-04-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0009_auto_20221006_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogsession',
            name='transmission_channel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
