# pylint: skip-file
# Generated by Django 3.2.16 on 2023-04-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0010_dialogsession_transmission_channel'),
        ('simple_messaging_dialog_support', '0010_dialogvariable_lookup_hash'),
    ]

    operations = [
    ]
