# pylint: skip-file
# Generated by Django 3.2.25 on 2025-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0011_merge_20230413_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogsession',
            name='latest_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
