# pylint: skip-file
# Generated by Django 5.2.4 on 2025-08-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0019_alter_dialogscriptversion_definition'),
        ('simple_messaging_dialog_support', '0012_alter_dialogsession_latest_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('dialog_script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_keywords', to='django_dialog_engine.dialogscript')),
            ],
        ),
    ]
