# pylint: skip-file
# Generated by Django 3.2.25 on 2025-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0013_launchkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchkeyword',
            name='launch_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchkeyword',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
