# pylint: skip-file
# Generated by Django 3.2.25 on 2026-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging_dialog_support', '0014_auto_20251009_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchkeyword',
            name='keyword',
            field=models.CharField(help_text='Uses literal string matching (not regexp). Use "*" as a catch-all.', max_length=256),
        ),
        migrations.AlterField(
            model_name='launchkeyword',
            name='launch_condition',
            field=models.TextField(blank=True, help_text='Evaluated by .dialog_api.launch_keyword_enabled functions.', null=True),
        ),
        migrations.AlterField(
            model_name='launchkeyword',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority keywords are evaluated first.'),
        ),
    ]
